apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  selector:
    name: postgres-app-pod
    app: demo-voting-app
  ports:
  - port: 5432
    targetPort: 5432
