apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deploy
  labels:
    name: redis-app-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: redis-app-pod
      labels:
        name: redis-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
                    